# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Qi_MOTUI.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1085, 852)
        Form.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(330, 10, 461, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setObjectName("label")
        self.evatextBrowser = QtWidgets.QTextBrowser(Form)
        self.evatextBrowser.setGeometry(QtCore.QRect(560, 680, 491, 141))
        self.evatextBrowser.setObjectName("evatextBrowser")
        self.origroupBox = QtWidgets.QGroupBox(Form)
        self.origroupBox.setGeometry(QtCore.QRect(30, 470, 451, 91))
        self.origroupBox.setObjectName("origroupBox")
        self.orib2 = QtWidgets.QRadioButton(self.origroupBox)
        self.orib2.setGeometry(QtCore.QRect(20, 20, 117, 22))
        self.orib2.setCheckable(True)
        self.orib2.setChecked(False)
        self.orib2.setObjectName("orib2")
        self.orib4 = QtWidgets.QRadioButton(self.origroupBox)
        self.orib4.setGeometry(QtCore.QRect(150, 20, 117, 22))
        self.orib4.setObjectName("orib4")
        self.orib5 = QtWidgets.QRadioButton(self.origroupBox)
        self.orib5.setGeometry(QtCore.QRect(280, 20, 117, 22))
        self.orib5.setObjectName("orib5")
        self.orib9 = QtWidgets.QRadioButton(self.origroupBox)
        self.orib9.setGeometry(QtCore.QRect(20, 40, 117, 22))
        self.orib9.setObjectName("orib9")
        self.orib10 = QtWidgets.QRadioButton(self.origroupBox)
        self.orib10.setGeometry(QtCore.QRect(150, 40, 117, 22))
        self.orib10.setObjectName("orib10")
        self.orib11 = QtWidgets.QRadioButton(self.origroupBox)
        self.orib11.setGeometry(QtCore.QRect(280, 40, 117, 22))
        self.orib11.setObjectName("orib11")
        self.orib13 = QtWidgets.QRadioButton(self.origroupBox)
        self.orib13.setGeometry(QtCore.QRect(20, 60, 117, 22))
        self.orib13.setObjectName("orib13")
        self.oriplay = QtWidgets.QPushButton(self.origroupBox)
        self.oriplay.setGeometry(QtCore.QRect(398, 60, 41, 27))
        self.oriplay.setObjectName("oriplay")
        self.oriother = QtWidgets.QRadioButton(self.origroupBox)
        self.oriother.setGeometry(QtCore.QRect(150, 60, 117, 22))
        self.oriother.setObjectName("oriother")
        self.newgraphicsView = QtWidgets.QGraphicsView(Form)
        self.newgraphicsView.setGeometry(QtCore.QRect(570, 70, 481, 391))
        self.newgraphicsView.setObjectName("newgraphicsView")
        self.newgroupBox = QtWidgets.QGroupBox(Form)
        self.newgroupBox.setGeometry(QtCore.QRect(580, 470, 461, 91))
        self.newgroupBox.setObjectName("newgroupBox")
        self.newb2 = QtWidgets.QRadioButton(self.newgroupBox)
        self.newb2.setGeometry(QtCore.QRect(30, 20, 117, 22))
        self.newb2.setChecked(False)
        self.newb2.setObjectName("newb2")
        self.newb4 = QtWidgets.QRadioButton(self.newgroupBox)
        self.newb4.setGeometry(QtCore.QRect(160, 20, 117, 22))
        self.newb4.setObjectName("newb4")
        self.newb5 = QtWidgets.QRadioButton(self.newgroupBox)
        self.newb5.setGeometry(QtCore.QRect(290, 20, 117, 22))
        self.newb5.setObjectName("newb5")
        self.newb9 = QtWidgets.QRadioButton(self.newgroupBox)
        self.newb9.setGeometry(QtCore.QRect(30, 40, 117, 22))
        self.newb9.setObjectName("newb9")
        self.newb10 = QtWidgets.QRadioButton(self.newgroupBox)
        self.newb10.setGeometry(QtCore.QRect(160, 40, 117, 22))
        self.newb10.setObjectName("newb10")
        self.newb11 = QtWidgets.QRadioButton(self.newgroupBox)
        self.newb11.setGeometry(QtCore.QRect(290, 40, 117, 22))
        self.newb11.setObjectName("newb11")
        self.newb13 = QtWidgets.QRadioButton(self.newgroupBox)
        self.newb13.setGeometry(QtCore.QRect(30, 60, 117, 22))
        self.newb13.setObjectName("newb13")
        self.newplay = QtWidgets.QPushButton(self.newgroupBox)
        self.newplay.setGeometry(QtCore.QRect(400, 60, 41, 27))
        self.newplay.setObjectName("newplay")
        self.newother = QtWidgets.QRadioButton(self.newgroupBox)
        self.newother.setGeometry(QtCore.QRect(160, 60, 117, 22))
        self.newother.setCheckable(True)
        self.newother.setChecked(False)
        self.newother.setObjectName("newother")
        self.groupBox_3 = QtWidgets.QGroupBox(Form)
        self.groupBox_3.setGeometry(QtCore.QRect(540, 570, 531, 101))
        self.groupBox_3.setObjectName("groupBox_3")
        self.evab2 = QtWidgets.QRadioButton(self.groupBox_3)
        self.evab2.setGeometry(QtCore.QRect(30, 30, 117, 22))
        self.evab2.setChecked(False)
        self.evab2.setObjectName("evab2")
        self.evab4 = QtWidgets.QRadioButton(self.groupBox_3)
        self.evab4.setGeometry(QtCore.QRect(160, 30, 117, 22))
        self.evab4.setObjectName("evab4")
        self.evab5 = QtWidgets.QRadioButton(self.groupBox_3)
        self.evab5.setGeometry(QtCore.QRect(290, 30, 117, 22))
        self.evab5.setObjectName("evab5")
        self.evab9 = QtWidgets.QRadioButton(self.groupBox_3)
        self.evab9.setGeometry(QtCore.QRect(420, 30, 117, 22))
        self.evab9.setObjectName("evab9")
        self.evab10 = QtWidgets.QRadioButton(self.groupBox_3)
        self.evab10.setGeometry(QtCore.QRect(30, 50, 117, 22))
        self.evab10.setObjectName("evab10")
        self.evab11 = QtWidgets.QRadioButton(self.groupBox_3)
        self.evab11.setGeometry(QtCore.QRect(160, 50, 117, 22))
        self.evab11.setObjectName("evab11")
        self.evab13 = QtWidgets.QRadioButton(self.groupBox_3)
        self.evab13.setGeometry(QtCore.QRect(290, 50, 117, 22))
        self.evab13.setObjectName("evab13")
        self.evaball = QtWidgets.QRadioButton(self.groupBox_3)
        self.evaball.setGeometry(QtCore.QRect(420, 50, 117, 22))
        self.evaball.setObjectName("evaball")
        self.evastart = QtWidgets.QPushButton(self.groupBox_3)
        self.evastart.setGeometry(QtCore.QRect(20, 70, 99, 27))
        self.evastart.setObjectName("evastart")
        self.a1Button = QtWidgets.QPushButton(Form)
        self.a1Button.setGeometry(QtCore.QRect(220, 610, 99, 27))
        self.a1Button.setObjectName("a1Button")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(30, 580, 141, 17))
        self.label_2.setObjectName("label_2")
        self.exitButton = QtWidgets.QPushButton(Form)
        self.exitButton.setGeometry(QtCore.QRect(950, 10, 99, 27))
        self.exitButton.setObjectName("exitButton")
        self.a2Button = QtWidgets.QPushButton(Form)
        self.a2Button.setGeometry(QtCore.QRect(220, 670, 99, 27))
        self.a2Button.setObjectName("a2Button")
        self.a3Button = QtWidgets.QPushButton(Form)
        self.a3Button.setGeometry(QtCore.QRect(220, 740, 99, 27))
        self.a3Button.setObjectName("a3Button")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(40, 610, 181, 17))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(40, 680, 151, 17))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setGeometry(QtCore.QRect(40, 740, 67, 17))
        self.label_6.setObjectName("label_6")
        self.datagroupBox = QtWidgets.QGroupBox(Form)
        self.datagroupBox.setGeometry(QtCore.QRect(30, 20, 221, 41))
        self.datagroupBox.setObjectName("datagroupBox")
        self.mot17radioButton = QtWidgets.QRadioButton(self.datagroupBox)
        self.mot17radioButton.setGeometry(QtCore.QRect(20, 20, 117, 22))
        self.mot17radioButton.setChecked(True)
        self.mot17radioButton.setObjectName("mot17radioButton")
        self.otherradioButton = QtWidgets.QRadioButton(self.datagroupBox)
        self.otherradioButton.setGeometry(QtCore.QRect(150, 20, 117, 22))
        self.otherradioButton.setObjectName("otherradioButton")
        self.progressBar1 = QtWidgets.QProgressBar(Form)
        self.progressBar1.setGeometry(QtCore.QRect(380, 610, 118, 23))
        self.progressBar1.setProperty("value", 24)
        self.progressBar1.setObjectName("progressBar1")
        self.progressBar2 = QtWidgets.QProgressBar(Form)
        self.progressBar2.setGeometry(QtCore.QRect(380, 670, 118, 23))
        self.progressBar2.setProperty("value", 24)
        self.progressBar2.setObjectName("progressBar2")
        self.progressBar3 = QtWidgets.QProgressBar(Form)
        self.progressBar3.setGeometry(QtCore.QRect(380, 740, 118, 23))
        self.progressBar3.setProperty("value", 24)
        self.progressBar3.setObjectName("progressBar3")
        self.orilabel = QtWidgets.QLabel(Form)
        self.orilabel.setGeometry(QtCore.QRect(40, 70, 481, 391))
        self.orilabel.setText("")
        self.orilabel.setObjectName("orilabel")
        self.origraphicsView = QtWidgets.QGraphicsView(Form)
        self.origraphicsView.setEnabled(True)
        self.origraphicsView.setGeometry(QtCore.QRect(40, 70, 481, 391))
        self.origraphicsView.setObjectName("origraphicsView")
        self.newlabel = QtWidgets.QLabel(Form)
        self.newlabel.setGeometry(QtCore.QRect(570, 70, 481, 391))
        self.newlabel.setText("")
        self.newlabel.setObjectName("newlabel")

        self.retranslateUi(Form)
        self.exitButton.clicked.connect(Form.close)
        self.a1Button.clicked.connect(Form.startProgress1)
        self.a2Button.clicked.connect(Form.startProgress2)
        self.a3Button.clicked.connect(Form.startProgress3)
        self.oriplay.clicked.connect(Form.oridatashow)
        self.newplay.clicked.connect(Form.newdatashow)
        self.evastart.clicked.connect(Form.evaluation)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "基于相关滤波和深度神经网络的多目标跟踪系统"))
        self.origroupBox.setTitle(_translate("Form", "原始数据展示"))
        self.orib2.setText(_translate("Form", "MOT17-02"))
        self.orib4.setText(_translate("Form", "MOT17-04"))
        self.orib5.setText(_translate("Form", "MOT17-05"))
        self.orib9.setText(_translate("Form", "MOT17-09"))
        self.orib10.setText(_translate("Form", "MOT17-10"))
        self.orib11.setText(_translate("Form", "MOT17-11"))
        self.orib13.setText(_translate("Form", "MOT17-13"))
        self.oriplay.setText(_translate("Form", "播放"))
        self.oriother.setText(_translate("Form", "其他"))
        self.newgroupBox.setTitle(_translate("Form", "多目标跟踪算法跟踪效果展示"))
        self.newb2.setText(_translate("Form", "MOT17-02"))
        self.newb4.setText(_translate("Form", "MOT17-04"))
        self.newb5.setText(_translate("Form", "MOT17-05"))
        self.newb9.setText(_translate("Form", "MOT17-09"))
        self.newb10.setText(_translate("Form", "MOT17-10"))
        self.newb11.setText(_translate("Form", "MOT17-11"))
        self.newb13.setText(_translate("Form", "MOT17-13"))
        self.newplay.setText(_translate("Form", "播放"))
        self.newother.setText(_translate("Form", "其他"))
        self.groupBox_3.setTitle(_translate("Form", "评估"))
        self.evab2.setText(_translate("Form", "MOT17-02"))
        self.evab4.setText(_translate("Form", "MOT17-04"))
        self.evab5.setText(_translate("Form", "MOT17-05"))
        self.evab9.setText(_translate("Form", "MOT17-09"))
        self.evab10.setText(_translate("Form", "MOT17-10"))
        self.evab11.setText(_translate("Form", "MOT17-11"))
        self.evab13.setText(_translate("Form", "MOT17-13"))
        self.evaball.setText(_translate("Form", "MOT17-ALL"))
        self.evastart.setText(_translate("Form", "开始评估"))
        self.a1Button.setText(_translate("Form", "算法1"))
        self.label_2.setText(_translate("Form", "多目标跟踪算法选择"))
        self.exitButton.setText(_translate("Form", "退出系统"))
        self.a2Button.setText(_translate("Form", "算法2"))
        self.a3Button.setText(_translate("Form", "算法3"))
        self.label_4.setText(_translate("Form", "CNN+LSTM+CF:"))
        self.label_5.setText(_translate("Form", "CNN:"))
        self.label_6.setText(_translate("Form", "LSTM:"))
        self.datagroupBox.setTitle(_translate("Form", "数据源"))
        self.mot17radioButton.setText(_translate("Form", "MOT17"))
        self.otherradioButton.setText(_translate("Form", "其他"))

